### ISSUE TITLE
jlink.online is offline

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/jlink.online#16]
https://jlink.online/ has been timing out for months. I don't know what the problem is and nobody I asked seems to know either. If anything more than a simple click of a button is required, we should revisit the whole setup and ensure that it can continue working without much baby sitting.

**Comment by cilki** [comment]
Sorry, I transferred the domain to AdoptOpenJDK quite a few months ago, so I'm not hosting it myself anymore. I'll need to work with someone who has infrastructure permissions to actually get it deployed once again.

**Comment by karianna** [comment]
@cilki - who did you liaise with?

**Comment by cilki** [comment]
@gdams helped me transfer the domain name back in April.

**Comment by aahlenst** [comment]
What are the requirements to host it? I looked at it in August or so and was wondering whether it could be easily reworked to use some sort of cloud functions.

**Comment by cilki** [comment]
It runs in a container, so there are many ways to host it. All I did in the past was drop it on AWS ECS and point the domain name to the container. Very simple, but there's still room for improvement.

The makefile should make it easy to build/push the container.

**Comment by aahlenst** [comment]
@gdams Can we throw it on OpenShift alongside the API? I like to keep the number of services we subscribe to low.

**Comment by smlambert** [comment]
@gdams - is there anything other TSC members can help you progress this?  it seems like a lost opportunity to not have this available for the community

**Comment by aahlenst** [comment]
It's running again, this time on AdoptOpenJDK's OpenShift:

```
$ curl -O -H "Host: jlink.online" https://elb.b9ad.pro-us-east-1.openshiftapps.com/x64/linux/11.0.8+10
```

Waiting for the right people to get the domain to work. The target container is built from master. A build has to be triggered manually at the moment if I see correctly. We can, if we want, automate it with a webhook.

**Comment by cilki** [comment]
@aahlenst Awesome! Is there a way I can monitor logs? It seems to be working pretty well, but I wouldn't be surprised if there are a few bugs left.

**Comment by gdams** [comment]
It's back online now

**Comment by aahlenst** [comment]
There are logs, but I don't know (yet, at least) whether we can give you access without opening up the entire account. OpenShift is new to me.

**Comment by gdams** [comment]
I'll take a look and see what we can do
