### ISSUE TITLE
Host Swagger Docs

### ISSUE THREAD

**Issue by cilki** [AdoptOpenJDK/jlink.online#17]
I think GitHub Pages should work well for hosting the API documentation. This template looks good: https://github.com/peter-evans/swagger-github-pages.

**Comment by gdams** [comment]
I'd rather host the swagger ui as part of the go application. I'm going to assume that there is a go package that can do that? That way we can keep the application all on one domain

**Comment by cilki** [comment]
We'd lose the ability to update docs independently of the application, but that's probably not a very big deal. I'll see what's out there that can do it.

**Comment by gdams** [comment]
We've got a webhook setup so any git changes will update the openshift cluster so that shouldn't be a problem

**Comment by cilki** [comment]
Looks like it will be easy to do, but I'll have to change the route of the main API in order to prevent a conflict with `/docs`.

It might be a good idea to further qualify that path anyway. I'm thinking something like `/runtime/linux/...` or `/download/linux/...`.

**Comment by gdams** [comment]
Here's what I suggest. We use a markdown rendering tool to return the README.md file for /

We then use /swagger-ui to host the swagger guide and link to it from the README

**Comment by cilki** [comment]
Thanks for the help on this one 👍.
