### ISSUE TITLE
Invalid runtimes kept in runtime cache

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/jlink.online#23]
#22 leaves partially extracted runtimes in the cache. For example, if the Linux archive fails to extract, I end up with the following contents in the runtime cache:

```
legal
release
```

As a result, jlinking can produce weird results. If I try to cross target Linux from a Windows JDK, jlink does not find the jmods in the Linux JDK and instead copies the Windows jmods. As a result, I end up with exe and dll files in a jlinked runtime for Linux. This behaviour by jlink is weird in itself, but nevertheless jlink.online should ensure that invalid runtimes do not end up in the cache.

**Comment by cilki** [comment]
Agreed. We could additionally ensure the `jmods` directory exists before passing it to jlink. As you noted, jlink uses the first module it finds, so that must always be the one from the target runtime.
