### ISSUE TITLE
Provide endpoint for health checks

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/jlink.online#30]
Would be great if there was an endpoint that could be used for health checks. Can be as simple as returning `{"status": "UP"}`. If there's more that could be done, for example looking at the space left in the runtime cache, great.

**Comment by cilki** [comment]
I noticed https://jlink.online/status doesn't return the free space left in the cache. The `df` in the container works as expected, so maybe `RT_CACHE` isn't setup correctly? That would also explain this response (https://jlink.online/runtime/x64/linux/11.0.8+10):
```
{"reason":"Failed to download local runtime","success":false}
```

If `RT_CACHE` isn't set, it tries to use `os.TempDir()`. I wonder if that could fail.

**Comment by aahlenst** [comment]
I mounted a persistent volume and configured RT_CACHE. It's too small, but that's not important right now. It's still using `/app/tmp/`. I'm not 100% sure, but I think this comes from the Dockerfile. So if we can remove `ENV TMP=/app/tmp`, the problem should go away.

**Comment by aahlenst** [comment]
I had to remove the volume again because it broke re-deployments. It was a single-user volume (RWO) and OpenShift does not unmount it when preparing a new container. A multi-user volume might be appropriate, but I first need to read the docs 😒

**Comment by cilki** [comment]
Looks like that last commit did the trick. Thanks!

**Comment by aahlenst** [comment]
Partially. We're now back to using `/tmp` which isn't persistent. And sharing the Dockerfile both for deployment and development might be uncomfortable. So either we put in some `ARG` or we put separate Dockerfiles into the repository.
