### ISSUE TITLE
the jlink.online app seems to be offline?

### ISSUE THREAD

**Issue by jexp** [AdoptOpenJDK/jlink.online#49]
@gdams this is what one currently gets?

<img width="1162" alt="Bildschirmfoto 2022-01-23 um 20 09 54" src="https://user-images.githubusercontent.com/67427/150694088-c24507e0-8748-44da-a461-2b7371e1d693.png">

Same when trying to access the endpoints via curl.

**Comment by gdams** [comment]
fixed now
