### ISSUE TITLE
Migrate to V3 API

### ISSUE THREAD

**Issue by cilki** [AdoptOpenJDK/jlink.online#9]
There are just three API calls in `adoptopenjdk.go` that need to be updated. It might also be possible to improve these functions with the new API at the same time.

**Comment by karianna** [comment]
@gdams as you pick up the jlinking work this might be appropriate.

**Comment by cilki** [comment]
I can do this one of course, but I thought it might also be a good opportunity to get the community involved.

**Comment by cilki** [comment]
I'm going to pick this back up in the next week or so if possible🤞.

**Comment by cilki** [comment]
In addition to moving to AdoptOpenJDK's V3 API, I've removed the eager cache that was introduced to address unreliability of the V2 API. Since release metadata still doesn't change very often, it will continue to be lazy-cached.
